graph/B13424_비밀모임_조승기.java, graph/B2458_키순서_조승기.java, 구현/B16236_아기상어_조승기.java, 구현/B2140_지뢰찾기_조승기.java
#2 #3 #5 #6 
<details>
키 순서 문제 bfs/dfs로 풀었습니다.
</div>
</details>
=> [승기] ~0219 알고리즘 풀이

0222/B1182_부분수열의합_조승기.java, 구현/B16234_인구이동_조승기.java, 구현/B17281_⚾_조승기.java
#13 #14 #15 
제 브랜치로 swtich 안 하고 메인에 작업하고 푸시해버렸습니다. 죄송합니다. revert 했습니다.
<details>
유형 비밀을 어느 폴더에 해야할지 모르기도 하고, 날짜별로 하면 좋을 것 같다는 의견에 
부분수열의 합 문제는 날짜 폴더에 커밋했습니다.
</div>
</details>
=> [승기] 0220 문제 SOLVE

0219/B1182_부분수열의합_김경호.java, 0219/B16234_인구이동_김경호.java, 0219/B17281_⚾_김경호.java, 구현/B16236_아기상어_김경호.java
#13 #15 #14 
<details>
</div>
</details>
=> [경호] 0219 문제 풀이

구현/B1182_부분수열의합_송인범.java, 구현/B16234_인구이동_송인범.java, 구현/B17281_⚾_송인범.java
#13 #14 #15 
- [o] 난이도 상 
<details>
</div>
</details>
=> [인범] 02.22 문제풀이

0226/B14502_연구소_김인엽.java
#21 
<details>
</div>
</details>
=> :sparkles: Add : BOJ 14502 연구소 #21

구현/B10972_다음순열_송인범.java, 구현/B10973_이전순열_송인범.java, 구현/B14502_연구소_송인범.java
#(21)
- [o ] 난이도 중
<details>
</div>
</details>
=> [#21][240226] BOJ 14502 연구소 G4

0226/B10972_다음순열_김인엽.java, 0226/B10973_이전수열_김인엽.java
#25 #28
<details>
</div>
</details>
=> [인엽] 0226 문제 풀이 #25

0226/B10972_다음순열_이찬민.java, 0226/B10973_이전순열_이찬민.java, 0226/B14502_연구소_이찬민.java
#(이슈번호)
#25 
#21 
#28 
<details>
</div>
</details>
=> [찬민] 0226 문제풀이

0226/B2457_공주님의정원_김경호.java
#32 
- [V] 문제를 풀었습니다. 
- [V] 난이도 상 
<details>
</div>
</details>
=> feat:공주님의정원

graph/B3197_백조의호수_송인범.java, greedy/S14510_나무높이_송인범.java, 구현/B17471_게리멘더링_송인범.java, 구현/B26170_사과빨리먹기_송인범.java
#31 #29 #35 #36 
- [o] 난이도 상 
<details>
늦게 제출합니다..
</div>
</details>
=> [인범]0304 문제풀이 #29 #31 #35 #36

0307/B20055_컨베이어벨트위의로봇_김인엽.java, 0307/P_불량사용자_김인엽.java, 0307/P_스킬트리_김인엽.java, 0307/P_유전법칙_김인엽.java
#42 #44 #45 #43 
<details>
요즘 에이징 커브 왔어요.. 
</div>
</details>
=> [인엽] 0307 PS

.gitignore, 0304/B20055_컨베이어벨트위의로봇_김경호.java, 0304/P_불량사용자_김경호.java, 0304/P_스킬트리_김경호.java
#43 #45 #42 
<details>
</div>
</details>
=> 0304 kkh algorithm

0307/B20055_컨베이어위의로봇_조승기.java, 0307/P불량사용자_조승기.java, 0307/P스킬트리_조승기.java
#45 #43 #44
<details>
</div>
</details>
=> [조승기] 3월7일 Solve

0311/B21610_마법사상어와비바라기_김인엽.java, 0311/P_영어끝말잇기_김인엽.java, 0311/P_의상_김인엽.java, 0311/P_전력망을둘로나누기_김인엽.java
#53 #54 #55 #56 
<details>
</div>
</details>
=> [인엽] 0311 PS #56 #55 #54 #53

0311/B21610_마법사상어와피바라기_송인범.java, 0311/P_영어끝말잇기_송인범.java, 0311/P_의상_송인범.java, 0311/P_전력망을둘로나누기_송인범.java
#53 #54 #55 #56
- [] 난이도 상 
- [o ] 난이도 중
<details>언제나 힘든 알고리즘
</div>
</details>
=> [인범] 03.11 PS #53 #54 #55 #56

0311/B21610_마법사상어와비바라기_이찬민.java, 0311/P영어끝말잇기_이찬민.java, 0311/P의상_이찬민.java, 0311/P전력망을둘로나누기_이찬민.java
#(이슈번호)
#56 #54 #53 #55 
<details>
</div>
</details>
=> 0311 Chanmin

0311/B21610_마법사상어비바라기_조승기.java, 0311/P_영어끝말잇기_조승기.java, 0311/P_의상_조승기.java, 0311/P_전력망을둘로나누기_조승기.java
#55 #56 #54 #53
<details>
</div>
</details>
=> [승기] 0311 Solve

0314/B_14500_테트로미노.java, 0314/P_조이스틱_송인범_실패.java, 0314/P_합승택시요금_송인범.java
#62 #63 #64
- [o ] 난이도 상 
담부터 조심히 내겠습니다 ^^
<details>
</div>
</details>
=> [인범] #62 #63 #64

0314/B14500_테트로미노_김인엽.java, 0314/P_합승택시요금_김인엽.java
#64 #62 
<details>
</div>
</details>
=> [0314] 인엽 PS #64 #62

0314/B14500_테트로미노_조승기.java, 0314/P_합승택시요금_조승기.java
#(62) #64
<details>
</div>
</details>
=> Seungki cho

0318/B4485_녹색옷입은애가젤다지_김경호.java, 0318/P_정수삼각형_김경호.java, 0318/P_타겟넘버_김경호.java
#70 #71 #72
<details>
</div>
</details>
=> [KH] 0318 김경호 #70 #71 #72

0318/B4485_녹색옷입은애가젤다지_김인엽.java, 0318/P_정수삼각형_김인엽.java, 0318/P_타겟넘버_김인엽.java
#70 #71 #72 
<details>
</div>
</details>
=> [인엽] 0318 PS #72 #71 #70

0321/B17779_게리맨더링2_김인엽.java
#78 
<details>
</div>
</details>
=> [인엽] #78 PS

0328/B17609_회문_송인범.java, 0328/B2565_전깃줄_송인범.java, 0328/L_MinimumSizeSubarraySum_송인범.java, 0328/P_멀리뛰기_송인범.java
#89 #82  #84  #85 
- [o ] 난이도 중
<details>
</div>
</details>
=> 0328 [inbum]

0328/L_minimumsizesubarraysum_조승기.java, 0328/P_멀리뛰기_조승기.java
#84 #85 
<details>
</div>
</details>
=> 0328 seungkicho

0328/B7579_앱_김인엽.java, 0328/P_멀리뛰기_김인엽.java
#86 #84 
<details>
</div>
</details>
=> [인엽] 0328 PS  #86 #84

0401/B2169_로봇조종하기_김경호.java, 0401/B2206_벽부수고이동하기_김경호.java, 0401/B9935_문자열폭발_김경호.java
#92 #93 #94 
<details>
</div>
</details>
=> Kkh 0401 solve

0401/B2206_벽부수고이동하기_김인엽.java, 0401/B9935_문자열폭발_김인엽.java
#93 #94 
<details>
</div>
</details>
=> [인엽] 0401 PS #93 #94

0404/B1744_수묶기_조승기.Java, 0408/B11049_행렬곱셈순서_조승기.java, 0408/B16496_큰수만들기_조승기.swift
https://github.com/Hwarang2Platinum/algorithm/issues/103 https://github.com/Hwarang2Platinum/algorithm/issues/102 https://github.com/Hwarang2Platinum/algorithm/issues/98
<details>
</div>
</details>
=> [0408] Sovle

0422/B1043_거짓말_조승기.java, 0422/B1629_곱셈_조승기.java
#(이슈번호)
<details>
</div>
</details>
=> [0422] Solve

240529/B1967_트리의지름_이찬민.java
#123 
<details>
</div>
</details>
=> [0529] Solve

240530/B14621_나만안되는연애_오화랑.java, 240531/B15651_N과M3_오화랑.java
#125
<details>
</div>
</details>
=> 240530_Badamandarin_Solve

240530/B14621_나만안되는연애_송인범
#125 
- [ o] 난이도 중
<details>
</div>
</details>
=> [240530] #125

240530/B14621_나만안되는연애_김경호.java
#125 
<details>
난이도는 어렵지 않았지만... 최소스패닝 트리인 것을 생각하지 못했다...
</div>
</details>
=> [0530] 나만안되는 연애 SOLVE!!

240530/B14621_나만안되는연애_이찬민.java
#125 
<details>
프림? 크루스칼? 진짜 기억안남
</div>
</details>
=> 240530 나만안되는연애 찬민

240531/B15651_N과M3_이찬민.java
#135 
<details>
</div>
</details>
=> 240531 chanmin

240531/B15651_N과M3_김인엽.java
#135 
<details>
</div>
</details>
=> #135 240531 N과M3 인엽

240531/B15651_N과M3_오화랑.java
#135 
<details>
</div>
</details>
=> 240531_ReCommit the Solved

240531/B15651_N과M3_조승기.java
#135
<details>
</div>
</details>
=> [240531] SSAFY MEET UP N과 M(3) 

240601/B17780_새로운게임_조승기.java
#132 
- 변수 덜 쓰려다가 한번 꼬였습니다. 클린 코드 실천하겠습니다.
=> [240601] 새로운 게임 조승기 SOLVE

240601/B17780_새로운게임_오화랑.java
#132 
<details>
문제를 바르게 읽어보자
</div>
</details>
=> Hwarang 240601 BOJ 17780 Solve

240601/B17780_새로운게임_김경호.java
#132 
<details>
k개이상쌓여야되는게 아니라 4개이상 쌓여야 되는 문제...
</div>
</details>
=> [240601] 새로운게임 김경호 SOLVE

240601/B17780_새로운게임_이찬민.java
#132 
어쨰서....!
<details>
</div>
</details>
=> 240601 chanmin

240602/B15652_N과M4_김인엽.java
#147 
<details>
</div>
</details>
=> 240603 N과M3 인엽 #147

240602/B1865_웜홀_송인범.py, 240603/B15652_N과M4_송인범.py
#143 #147 
- [o ] 난이도 상 
<details>
13번 넘게 틀림
</div>
</details>
=> #143 #147 [인범]

240530/B14621_나만안되는연애_김종호.java, 240602/B1865_웜홀_김종호.java
#143 
<details>
플로이드 워셜로 억지로 품
</div>
</details>
=> daily: 240602 B1865 웜홀 김종호

240602/B1865_웜홀_김경호.java, 240605/B1238_파티_김경호.java
#143 
#151 
<details>
- 웜홀
벨만포드 문제
1. 벨만포드 잘 기억안남 =>  정점V-1 * 모든 간선!
2. 벨만포드에서 음의간선 추출 알고리즘 (마지막에 한사이클 추가 했을 때 갱신여부)
3. 모든 정점이 연결되어있다는 보장이 없기 때문에 방문여부 확인해서 방문하지 않은 정점을 시작정점으로 해서 돌려봐야함
즉, 시작정점을 한 정점으로 고정해두고 시작하면 안됨
</div>
</details>
=> 240602,240605 웜홀, 파티 SOLVE

240605/B1238_파티_오화랑.java, 240606/B2096_내려가기_오화랑.java
#151 
<details>
조금 더, 시간적으로 유리하게 풀고자 고민을 하고 있습니다..
</div>
</details>
=> 240605 Solve BOJ 1238 Party Hwarang

240605/B1238_파티_김종호.java, 240606/2096_내려가기_김종호.java
#151
#156 
<details>
X에서 출발하는 다익스트라 한번 먼저 하고 다른 출발지에서 X 까지 가는 최단거리를 모두 구한다.
</div>
</details>
=> daily: 240605 B1238 파티 김종호

240606/B2096_내려가기_김경호.java
#156 
<details>
* 메모라이제이션
* 현재 depth의 3 요소는 각각 이전 depth에서의 최대, 최소들이 들어있다.
* 현재 depth의 3요소중 최대, 최소를 반환하자.
*
* 주의사항 !! : 게임 점수 0이 가능하므로 dp의 초기값을 0으로 하면 모든 보드가 0일 경우
* dp가 무용지물이 되어 엄청나게 돌 것이다 그래서 시간초과 남.
</div>
</details>
=> 240606 내려가기 SOLVE

240603/B15652_N과M4_송인범.py, 240605/B1238_파티_송인범.py, 240606/B2096_내려가기_송인범
#151  #156 
- [ 0] 난이도 상 
<details>
</div>
</details>
=> [inbum] #151 #156

240607/B1918_후위표기식_김경호.java
#160 
<details>
규칙 보고 풀음
</div>
</details>
=> 240607 후위표기식 SOLVE

240607/B1918_후위표기식_조승기.java
#160
<details>
</div>
</details>
=> [240607] 후위표기식 조승기

240607/B1918_후위표기식_김종호.java, 240608/B9465_스티커_김종호.java
#160 
#170 
<details>
</div>
</details>
=> daily: 240607 B1918 후위표기식 김종호

240608/B9465_스티커_김경호.java
#170 
<details>
dp문제 -  top-down 으로 해결
.
dp 배열
- 스티커의 첫번째 선택했을 때 dp[depth][0]
- 스티커의 두번째 선택했을 때 dp[depth][1]
- 스티커중 선택 안했을 때 dp[depth][2]
dfs 함수
- pointer
- 현재 depth 에서 선택한 스티커 0은 첫번째, 1은 두번째, 2는 아무것도 선택 안함
- 현재 depth에서 첫번째 스티커 선택했다 -> (다음스티커의 두번째 스티커 선택 , 선택x 중 큰값) + 현재 선택 스티커 점수
- 현재 depth에서 두번째 스티커 선택했다 -> (다음스티커의 첫번째 스티커 선택 , 선택x 중 큰값) + 현재 선택 스티커 점수
- 현재 depth에서 스티커 선택안했다 -> 다음스티커의 첫번째 스티커 선택 , 다음스티커의 두번째 스티커 선택 중 큰값
</div>
</details>
=> 240608 스티커 SOLVE

240608/B9465_스티커_조승기.java, 240609/B1167_트리의지름_조승기.java, 240610/B11404_플로이드_조승기.java
#(이슈번호)
- 스티커 - 중
- bottom-up 으로 푸니까 어려웠습니다.
- 트리의 지름 - 중
<details>
</div>
</details>
=> [240610] 플로이도 스티커 트리의지름

240609/B1167_트리의지름_송인범.py, 240610/B11404_플로이드_송인범.py
#174 #171 
- [o] 난이도 중
<details>
</div>
</details>
=> [inbum] #174 #171

240610/B11404_플로이드_김인엽.java
#174 
<details>
</div>
</details>
=> 240610 solve

240609/B1167_트리의지름_오화랑.java, 240610/B11404_플로이드_오화랑.java
#171 
<details>
유사한 문제가 나간 적이 있어서, 덜 헤맬 수 있었음.
코테 개털리고, 이제 자동완성 끄고 풀고 있음. 코드 양식도 코테랑 맞춰서 풀려고 함.
</div>
</details>
=> 240609 BOJ 1167 Hwarang Solve

240609/B1167_트리의지_김종호.java, 240610/B11404_플로이드_김종호.java
#171 
#174 
<details>
</div>
</details>
=> daily: 240609 B1167 트리의 지름 김종호

240611/B4195_친구네트워크_김인엽.java
#177 
<details>
</div>
</details>
=> 240611 친구네트워크 solve

240611/B4195_친구네트워크_오화랑.java
#177 
<details>
Hashing을 필요로 하는 문제 + Union Find를 경험할 수 있는 문제였음
Union Find Code를 제대로 숙지하지 못했기에, 구현에 어려움은 있었으나
아이디어 자체는 금방 생각나는 문제였던것 같다.
</div>
</details>
=> 240611 BOJ 4195 Hwarang Solve

240611/B1004_어린왕자_김종호.java
#178 
<details>
</div>
</details>
=> daily: 240611 B1004 어린왕자 김종호

240609/B1167_트리의지름_송인범.py, 240611/B4195_친구네트워크_송인범.py, 240612/B1004_어린왕자_송인범.py
#177 #178 
- [o] 난이도 중
<details>
</div>
</details>
=> [inbum] #177 #178

240612/B1004_어린왕자_김인엽.py
#178 
<details>
</div>
</details>
=> 240612 어린왕자 solve

240613/B2513_통학버스_조승기.java
#186 
<details>
</div>
</details>
=> [240613] 통학버스

240612/B2513_통학버스_김종호.java, 240612/B4195_친구네트워크_김종호.java
#186 
<details>
</div>
</details>
=> daily: 240613 B2513 통학버스 김종호

240610/B11404_플로이드_김경호.java, 240613/B2513_통학버스_김경호.java, 240614/B14890_경사로_김경호.java
#186 #190 
<details>
</div>
</details>
=> 240613,14 통학버스, 경사로 SOLVE

240613/B2512_통학버스_오화랑.java, 240614/B14890_경사로_오화랑.java
#186  
#190 
<details>
통학 버스 : Greedy 치고는 쉽게 규칙을 찾아내서, 할 수 있던 것 같다. 그렇지만 자료구조가 조금 빡세서, 개인적으로 구현이 더 걸림
경사로 : 이것도 나름 규칙이 쉽게 나와서 할 수 있는데, 한번 Code 엎고 정리해서 풀었다. 실전이었음, 중간에 오류 계속 터지다가 못풀었을 듯
</div>
</details>
=> 240613_240614 BOJ 2512, 14890 Hwarang Solve

240613/B2513_통학버스_송인범.py, 240614/B14890_경사로_송인범.java
#190 #186 
- [ o] 난이도 상 
<details>
</div>
</details>
=> [inbum] #190 #186

240615/B15684_사다리조작_송인범.py, 240616/B14488_준오는급식충이야_송인범.py
#194 
- [o] 난이도 상 
<details>
아니 내일 비형 특강 첫날인데 이문제때문에 3시 넘어서 자네욥ㅠㅠ..
</div>
</details>
=> [inbum] #194

240615/B15684_사다리조작_오화랑.java, 240616/B14488_준오는급식충이야_오화랑.java
#194 #197 
<details>
</div>
</details>
=> 240616 Hwarang Alg Solve

240617/B1907_알파벳_송인범.py, 240618/B1052_물병_송인범.py
#198 
- [ o] 난이도 상 
<details>
파이썬 시간초과, 메모리 초과 너무 많이 뜬다..
다음부터 파이썬 인권 보장되는 문제좀 ..
DFS 문제인데 BFS로 해야되는게 말이야 방구야!
</div>
</details>
=> [inbum] 198 fail

240618/B1052_물병_조승기.java, 240619/B23326_홍익투어리스트_조승기.java
#204 #203 
- 홍대 투어리스트 - 중
<details>
</div>
</details>
=> [240618] 물병 [240619] 홍익대학교 투어리스트

240614/B14890_경사로_김인엽.java, 240617/B1907_알파벳_김인엽.java, 240618/B1052_물병_김인엽.java
#198 #190 #203
- [] 문제를 풀었습니다. 
<details>
알파벳 빼고 다 답봤습니다,,, ㅠㅠ
</div>
</details>
=> 경사로, 알파벳, 물병 solve?

240615/B15684_사다리조작_오화랑.java, 240617/B1987_알파벳_오화랑.java
#198 
<details>
특이한 DFS 형태의 문제
</div>
</details>
=> 240617 BOJ 1987 Hwarang Solve

240617/B1987_알파벳_김경호.java, 240618/B23326_홍익투어리스트_김경호.java
#204 #198
<details>
</div>
</details>
=> 240619 SOLVE

240620/B13418_학교탐방하기_조승기.java
#206 
<details>
</div>
</details>
=> [240620] 학교 탐방하기

240618/B1052_물병_오화랑.java
#203 
<details>
조건을 제대로 파악하지 못해서 많이 고생했네요,,
</div>
</details>
=> 240618_Hwarang BOJ 1052 Alg Solve

240619/B13418_학교탐방하기_김경호.java
#206 
<details>
MST문제
크루스칼 알고리즘(union-find)로 풀음
</div>
</details>
=> 240620 학교탐방하기 SOLVE

240621/B31091_거짓말_송인범.py, 240622/S_출퇴근길_송인범.py
#215
- [o ] 난이도 중
<details>
재귀 호출 깊이를 정하는 것이 정답이다.
</div>
</details>
=> #215 [inbum]

240621/B31091_거짓말_오화랑.java
#212 
<details>
약간 사람을 화나게 만드는 문제다. 이런 것들을 대비하는 것이 좋은 것 같다 
</div>
</details>
=> 240621 BOJ 31091 Hwarang Solve

240623/B11437_LCA_오화랑.java
#217 
<details>
아예 처음 보는 유형이라, 많이 어려웠다.
시간 초과를 몇번이나 보았는 지 모르겠음
아이디어가 생각이 나도, Depth를 어떻게 해야 하는 지 몰라 개념을 챙겨보았다.
</div>
</details>
=> 240623 BOJ 11437 Hwarang Solve

240624/B1749_점수따먹기_송인범.py
#221
- [o] 난이도 상 
<details>
원하는 연속된 수열을 구하는 식이 좀 까리하다.
</div>
</details>
=> #221 [inbum]

240627/B2003_수들의합2_김인엽.java, 240628/B21921_블로그_김인엽.java
#228 #229
<details>
</div>
</details>
=> 240627, 28 수들의 합 2, 블로그 solve #228, #229

240626/B20437_문자열게임2_송인범.py, 240627/B2003_수들의합2_송인범.py, 240628/B21921_블로그_송인범.py
#228 #229
- [o] 난이도 하
<details>
</div>
</details>
=> #228 #229 [inbum]

240629/B28108_시간이겹칠까_송인범.py, 240629/temp.py
#234 
- [o] 난이도 중
<details>
</div>
</details>
=> Inbum #234

240624/B1749_점수따먹기_오화랑.java, 240625/B4920_테트리스게임_오화랑.java, 240626/B20437_문자열게임2_오화랑.java, 240627/B2003_수들의합2_오화랑.js, 240628/B21921_블로그_오화랑.js
#221 #224 #226 #228 #229 
<details>
</div>
</details>
=> 240630_Hwarang_solve Lot

240629/B28018_시간이겹칠까_오화랑.js
#234
<details>
</div>
</details>
=> 240630 B28108 Hwarang Solve

240630/B16719_ZOAC_오화랑.js
#232
<details>
참.. 재미있었던^^ 문자열 문제
</div>
</details>
=> 240630 B16719 Hwarang Solve

240630/B16719_ZOAC_송인범.py
#232 
- [ o ] 난이도 중
<details>
발상을 할 수 있으면 쉬운 문제.. 하지만 어려움
</div>
</details>
=> #232 [inbum]

240702/P_석유시추_김경호.java
#240 
<details>
- 성능개선
- 석유부분에 대해서 bfs를 하고 해당 bfs를 하는동안 방문한 열에 해당 석유개수를 더해준다.
</div>
</details>
=> 240702 석유시추 SOLVE

240701/B13302_리조트_송인범.py, 240701/temp.py, 240702/P_석유시추_송인범.py
#240 
- [o] 난이도 중
<details>
경호의 도움을 받음.
</div>
</details>
=> #240 [inbum]

240702/P_석유시추_김인엽.py
#240 
<details>
</div>
</details>
=> 240702 석유시츄 solve

240720/B5052_전화번호목록_송인범.py
#255 
- [o] 난이도 상 
<details>
Trie 연습 문제였습니다. 물론 저도 못풀었는데 답지 보면서 어떤 건지 익히는 데 중점을 두었습니다. 
</div>
</details>
=> #255 inbum solve

240902/B2075_N번째큰수_조승기.swift
#257
- 아래가 무조건 작다는 조건으로 풀려고 하다가 안풀려서 heap으로 했는데 풀리네요
- 팀장님의 다양성을 위해 Swift로 풀어라 라는 명령 하에 swift로 제출합니다.
=> Daily: 240902 B2075_N번째큰수_조승기

240902/B2075_N번째큰수_김인엽.java
#257 
<details>
</div>
</details>
=> Daily: 240902 B2075_N번째큰수_김인엽.java #257

240902/B2075_N번째큰수_김종호.java, 240903/B2583_영역구하기_김종호.java
#257 
#259 
<details>
</div>
</details>
=> Daily: 240902 B2075_N번째큰수_김종호.java, 240903 B2583_영역구하기_김종호.java

240904/B1261_알고스팟_김종호.java
#260 
<details>
</div>
</details>
=> Daily: 240904 B1261_알고스팟_김종호.java

240902/B2075_N번째큰수_송인범.py, 240903/B2583_영역구하기_송인범.py, 240904/B1261_알고스팟_송인범.py, 240905/B6588_골드바흐의추측_송인범.py, 240906/B2529_부등호_송인범.py
#263 #261 #260 #259 #257
- [o] 난이도 하
<details>
오랜만에 문제를 풀었습니다.
다양한 유형에서 문제를 풀어서 재밌었습니다.
</div>
</details>
=> #263 #261 #260 #259 #257 inbum

240906/B2529_부등호_김종호.java
#263 
<details>
</div>
</details>
=> Daily: 240905 B2529_부등호_김종호.java

240903/B2583_영역구하기_김인엽.java, 240904/B2529_부등호_김인엽.java, 240905/B6588_골드바흐의_추측_김인엽.java
#259 
#261 
#263
<details>
골드바흐는 답봤어여
</div>
</details>
=> 1주차: #259 #261 #263

2409_1주차/B1261_알고스팟_조승기.java, 2409_1주차/B2529_부등호_조승기.java, 2409_1주차/B2583_영역구하기_조승기.swift, 2409_1주차/B6588_골드바흐의추측_조승기.java
=> [2409_1주차] 영역 구하기, 알고스팟, 골드바흐의 추측, 부등호

2409_2주차/B14940_쉬운최단거리_김종호.java
#277 
<details>
</div>
</details>
=> Daily: 240909 B14940_쉬운최단거리_김종호.java

2409_2주차/B2531_회전초밥_김종호.java
#276 
<details>
</div>
</details>
=> Daily: 240909 B2531_회전초밥_김종호.java

2409_2주차/B5972_택배배송_김종호.java
#(이슈번호)
<details>
</div>
</details>
=> Daily: 240909 B5972_택배배송_김종호.java

2409_3주차/P_3차자동완성_김정규.java, 2409_3주차/P_네트워크_김정규.java, 2409_3주차/P_당구연습_김정규.java
P_당구연습 https://school.programmers.co.kr/learn/courses/30/lessons/169198
P_네트워크 https://school.programmers.co.kr/learn/courses/30/lessons/43162
P_3차자동완성 https://school.programmers.co.kr/learn/courses/30/lessons/17685
=> docs: 문제 업로드

2409_2주차/B14940_쉬운최단거리_김인엽.java, 2409_2주차/B15989_123더하기4_김인엽.java, 2409_2주차/B2531_회전초밥_김인엽.java, 2409_2주차/B5972_택배배송_김인엽.java
#276 #277 #278 #279
<details>
</div>
</details>
=> [2409_2주차] solve : #276 #277 #278 #279 + 3주차 디렉토리 넣기

2409_2주차/B14940_쉬운최단거리_송인범.py, 2409_2주차/B15989_123더하기4_송인범.py, 2409_2주차/B2531_회전초밥_송인범.py, 2409_2주차/B5972_택배배송_송인범.py
#276 #277 #278 #279
- [ o] 난이도 중
<details>
</div>
</details>
=> #276 #277 #278 #279 inbum

2409_2주차/B15989_123더하기4_김종호.java
#279 
<details>
</div>
</details>
=> Daily: 240911 B15989_123더하기4_김종호.java

2409_2주차/B14940_쉬운최단거리_조승기.java, 2409_2주차/B15989_123더하기4_조승기.java, 2409_2주차/B2531_회전초밥_조승기.java, 2409_2주차/B5972_택배배송_조승기.java
#(이슈번호)
호다닥
<details>
</div>
</details>
=> 2주차 조승기 feat: #276, #277, #278, #279

2409_2주차/B14940_쉬운최단거리_오화랑.java, 2409_2주차/B14940_쉬운최단거리_오화랑.js, 2409_2주차/B15989_123더하기4_오화랑.js, 2409_2주차/B2531_회전초밥_오화랑.js, 2409_2주차/B5972_택배배송_오화랑.java
#279 #278 #277 #276 
<details>
생각보다 어려웠어용.. 그래프 오랜만임!
그리고, 생각하지 몬한 함정도 있어서 재밌게 했습니다!
</div>
</details>
=> ✨ feat : 9월 2주차 Algorithm 풀이

2409_3주차/P_네트워크_오화랑.js, 2409_3주차/P_당구연습_오화랑.js, 2409_3주차/P_자동완성_오화랑.js
#293 #294 #295 
<details>
굉장하게 재밌는 시간이었다. 특히 당구 연습과 자동 완성은, 매우 재미가.. 있는..ㅠㅠ
=> 그래도, 이런 기법을 알아두면, 여러 코테에서도 쓰일 것 같다:)
</div>
</details>
=> ✨ solve : 오화랑 3주차 Algorithm Solved

2409_3주차/P_네트워크_김종호.java, 2409_3주차/P_자동완성_김종호.java
#294 #293  
<details>
</div>
</details>
=> 3주차 알고리즘 풀이 #294 #293

2409_3주차/P_네트워크_김경호.java, 2409_3주차/P_자동완성_김경호.java
#293 #294 
<details>
당구게임 어려워서 답봄 포기할래여
</div>
</details>
=> 9월 3주차 김경호 solve #293 #294 

2409_3주차/P_네트워크_송인범.py, 2409_3주차/P_당구연습_송인범.py, 2409_3주차/P_자동완성_송인범.py
#293 #294 #295
- [o] 난이도 상 
<details>
색다른 유형이 많이 나와서 푸는 느낌보다는 배우는 느낌으로 제출합니다:)
</div>
</details>
=> #293 #294 #295 인범

2409_3주차/P_네트워크_김인엽.java, 2409_3주차/P_당구연습_김인엽.java, 2409_3주차/P_자동완성_김인엽.java
#293 #294 #295
<details>
</div>
</details>
=> [9월 3주차] solve : 2409 #293 #294 #295

2409_3주차/P_3차자동완성_조승기.java, 2409_3주차/P_네트워크_조승기.java, 2409_3주차/P_당구연습_조승기.swift
#(이슈번호)
<details>
</div>
</details>
=> [조승기] 당구연습 네트워크 자동완성

2409_4주차/B10159_저울_김인엽.java, 2409_4주차/B17299_오등큰수_김인엽.java, 2409_4주차/B3184_양_김인엽.java
#302 #303 #304
<details>
오등큰수는 답 봤어요 ㅠㅠ
</div>
</details>
=> #302, #303, #304 2409_4주차_인엽

2409_4주차/B10159_저울_송인범.py, 2409_4주차/B17299_오등큰수_송인범.py, 2409_4주차/B3184_양_송인범.py
#302  #303  #304
- [o] 난이도 중
<details>
</div>
</details>
=> #302, #303, #304 2409_4주차_인범

2409_4주차/B3184_양_김경호.java
#302  #303  #304 
<details>
오등큰수 유형 참고함...
저울은 답봄..
</div>
</details>
=> #302, #303, #304 2409_4주차_경호

2410_1주차/B3107_IPV6_송인범.py, 2410_1주차/B32408_대전도시철도2호선_송인범.py, 2410_1주차/P_충돌위험찾기_송인범.py
#310  #311  #312 
- [O] 난이도 상 
<details>
난이도 조절 실패
아임 쏘리
</div>
</details>
=> 2410_1주차 송인범

2410_1주차/B3107_IPV6_조승기.java, 2410_1주차/B32408_대전도시철도2호선_조승기.java, 2410_1주차/P_충돌위험찾기_조승기.java
#310 #311 #312
<details>
- 성심당은 어렵네요.. 도움받았습니다.
</div>
</details>
=> 24/10/1주차 조승기

2410_1주차/B3107_IPV6_조승기.java, 2410_1주차/B32408_대전도시철도2호선_조승기.java, 2410_1주차/P_충돌위험찾기_조승기.java, 2410_2주차/B1402_아무래도이문제는A번난이도인것같다_조승기.java, 2410_2주차/B2183_테니스시합_조승기.java
문제들이 신기하네요
#315 #316
<details>
</div>
</details>
=> 24/10/2주차 조승기

2410_3주차/B1325_효율적인해킹_김인엽.java, 2410_3주차/B13905_세부_김인엽.java, 2410_3주차/B16169_수행시간_김인엽.py
#320 #318 #319
<details>
- 수행시간, 세부는 답 봤어요! 크루스칼,,,
</div>
</details>
=> :sparkles: Solve 10월 3주차

2409_4주차/B10159_저울_김경호.java, 2409_4주차/B17299_오등큰수_김경호.java, 2410_1주차/B3107_IPv6_김경호.java, 2410_3주차/B1325_효율적인해킹_김경호.java, 2410_3주차/B13905_세부_김경호.java, 2410_3주차/B16169_수행시간_김경호.java
#318 #319 #320 
<details>
so difficult
</div>
</details>
=> Solve 10월 3주차

2410_3주차/B13905_세부_오화랑.java, 2410_3주차/B16169_수행시간_오화랑.java
#318 #319 # 
<details>
✨ solve : 마지막 효율적인 해킹은 다른 방법으로 접근해야 겠음!!
</div>
</details>
=> ✨ solve : 2410_3주차 : 마지막 효율적인 해킹은 다른 방법으로 접근해야 겠음!!

2410_4주차/B11758_CCW_김인엽.java, 2410_4주차/B1743_음식물피하기_김인엽.java, 2410_4주차/B9466_텀프로젝트_김인엽.java
#324 #325 #326
<details>
</div>
</details>
=> Solve: 10월 4주차

2410_5주차/B15486_퇴사2_오화랑.java, 2410_5주차/B15990_123더하기5_오화랑.java, 2410_5주차/B1600_말이되고픈원숭이_오화랑.java
#328 #329 #330 
<details>
아찔했습니다..
</div>
</details>
=> ✨ Solve : 2410_5주차 Problem Solved

2410_4주차/B11758_CCW_송인범.py, 2410_4주차/B1743_음식물피하기_송인범.py, 2410_4주차/B9466_텀프로젝트_송인범.py
#324 #325 #326 
- [o] 난이도 상 
<details>
어려운 난이도가 많다..
</div>
</details>
=> #324 #325 #326 inbum solve

.github/workflows/daily_alorithm.yml, .gitignore, 2411_4주차/B13144_ListOfUniqueNumbers_오화랑.java, 2411_4주차/B14426_접두사찾기_오화랑.java, 2411_4주차/B15686_치킨배달_오화랑.java, package-lock.json, package.json, update-algorithm-issue.js
✅ 1. 접두사 찾기 : Trie 구조가 아니면, 거의 안풀리는 것 같음
✅ 2. LOUN : Two Pointer 접근을 통해 해결
✅ 3. 치킨 배달 : 순조부 문제 연습에 좋음
#335 #336 #334 
<details>
</div>
</details>
=> ✨ Solved 2411_4주차 Problems

package.json
#(이슈번호)
<details>
</div>
</details>
=> 🐛 bugfix : 의존성 추가

generate_hint.js, generate_problem.js, package-lock.json, package.json, update_project_issue.js
✅  OpenAI 힌트 생성 기능 추가
OpenAI API를 활용해 알고리즘 문제의 해결 힌트를 자동으로 생성하는 기능을 추가하였습니다. 이 기능은 문제 해결 과정을 지원하고 주요 논리 코드 작성에 도움을 줍니다.
✅ 문제 추천 기준 업데이트
문제 추천 알고리즘의 Query를 변경했습니다.
✅ 오탈자 검수
중간에 있던 몇몇 string value 오탈자 검수함.
기능 설명의 가독성을 높이기 위해 문장 구성을 다듬음.
=> ✨ feat : OpenAI 힌트 생성 및 문제 추천 기준 업데이트
